[project]
name = "backend"
version = "0.1.0"
description = "backend for the website cloner"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.110",
    "uvicorn[standard]>=0.27",
    "accelerate>=0.29.0"
]
